---
title: "Developing Data Products- Week 3 Assignment"
output: html_document
---

<html>
<head>
<h5>Nishant Sirohi</h5>
<h6>03/11/2020</h6>
<style>
body{
background-color: blue;
}
h5{
color: purple;
background-color: yellow;
}
h1{
color: cyan;
}
h6{
background-color: yellow;
color: red;
}
h2{
color: cyan;
}
p{
color: cyan;
}
</style>
</head>
<body>
Settings
----
We are going to plot 'Mileage per gallon' vs 'Weight (1000 lbs)', by '# of cylinders'
```{r, eval=FALSE}
library(plotly)
```
```{r, echo=FALSE}
library(plotly)
```

Settings (cont.)
----
```{r, echo=TRUE}
f <- list(
  family = "Courier New, monospace",
  size = 11,   color = "#6e6e6e" )
x <- list(
  title = "Weight (1000 lbs)",   titlefont = f )
y <- list(
  title = "Mileage per gallon",   titlefont = f )
```

```{r , eval=FALSE}
plot_ly(mtcars, x = mtcars$wt, y=mtcars$mpg, mode="markers", 
        type="scatter",color=as.factor(mtcars$cyl), size=mtcars$hp ) %>%   
        layout(xaxis=x, yaxis=y)
```


Plotting
----
```{r , echo=FALSE}
plot_ly(mtcars, x = mtcars$wt, y=mtcars$mpg, mode="markers",showlegend=TRUE, 
        type="scatter",color=as.factor(mtcars$cyl), size=mtcars$hp ) %>%   
        layout(xaxis=x, yaxis=y)
```
</body>
</html>